### ISSUE TITLE
Create a cleanup job based on specified retention days

### ISSUE THREAD

**Issue by aldy505** [getsentry/vroom#268]
Regarding https://github.com/getsentry/self-hosted/pull/2154#discussion_r1210881838:

> BYK It's definitely an issue we didn't really think about since we were relying on GCS retention settings to remove profiles when needed. I should be addressed separately in vroom.

On sentry and snuba image, they both respect `SENTRY_EVENT_RETENTION_DAYS` environment variable in which will automatically delete the data longer than the provided retention days. While the self-hosted version of vroom rely on filesystem, should we create a simple goroutine (instead of having it as a separate process -- which will add a new container on the self-hosted docker-compose) that will do a cleanup job everyday?

**Comment by aldy505** [comment]
Any thoughts? @phacops

**Comment by phacops** [comment]
Depending on where you host, this is probably handled better differently. I'd say we can start by making a job handling the filesystem case. If you're on a cloud provider, you probably should have it using retention parameters of S3/ABS/GCS.

If we focus on the filesystem case, we could likely start with implementing this in `self-hosted` directly by launching a container from this image (https://github.com/getsentry/self-hosted/blob/master/cron/Dockerfile) and then, every 6h, run this command:
```sh
find <vroom volume> -mtime +<retention days> -delete
```

If we need something more generic (which, I'm against since it's better handled differently for each cloud providers), we'll make a new command in this repository, listing files needing to be deleted from ClickHouse and we'll use the library we have to delete them.

**Comment by phacops** [comment]
Indeed, we have a lot of containers. We could reuse an existing container running a cron and just adding the cron definition in it (I'm thinking about the symbolicator cleanup job).

**Comment by aldy505** [comment]
I'd prefer to have a dedicated container for vroom. I don't think it makes sense if we're adding another definition on existing cron container.

I'll make a PR soon on self-hosted to address this.

**Comment by aldy505** [comment]
Handled on self-hosted. https://github.com/getsentry/self-hosted/pull/2211
